spring:
  datasource:
    url: jdbc:postgresql://kala.db.elephantsql.com:5432/bvmfhbbh
    username: bvmfhbbh
    password: TWq74lbb6WbYZVzohQ8vihJF6NjYAaGv
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      idle-timeout: 30000
      connection-timeout: 30000

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true